system:
  phase_models: Cr-Ni_phases.json
  datasets: input-data
  tags:
    dft:
      excluded_model_contributions: ['idmix', 'mag']
      weight: 0.1
    nomag:
      excluded_model_contributions: ['mag']
    estimated-entropy:
      excluded_model_contributions: ['idmix', 'mag']
      weight: 0.1
generate_parameters:
  excess_model: linear
  ref_state: SGTE91
  aicc_penalty_factor:
    BCC_A2:
      HM: 2.0
      SM: 2.0
    LIQUID:
      HM: 10
      SM: 10
output:
  verbosity: 1
  output_db: generated-aicc.tdb
