system:
  phase_models: Cr-Ni_phases.json
  datasets: input-data
  tags:
    dft:
      excluded_model_contributions: ['idmix', 'mag']
      weight: 0.1
    nomag:
      excluded_model_contributions: ['mag']
    estimated-entropy:
      excluded_model_contributions: ['idmix', 'mag']
      weight: 0.1
output:
  output_db:  mcmc.tdb
  verbosity:  2
  tracefile:  Cr-Ni-trace.npy
  probfile:   Cr-Ni-lnprob.npy
  logfile:    Cr-Ni-mcmc.log
mcmc:
  iterations: 3
  approximate_equilibrium: True
  save_interval: 1
  scheduler: dask  # run in parallel 
#   cores: 4  # number of cores (chooses all by default)
  input_db: mcmc-start.tdb
  chains_per_parameter: 4
  data_weights:
    ZPF: 40.0
    SM: 0.1